#!/usr/bin/env python
from __future__ import print_function
import bokeh.server.start
import bokeh.server
if __name__ == "__main__":
    try:
        bokeh.server.run()
    except KeyboardInterrupt:
        bokeh.server.start.stop()
        print("Shutting down bokeh-server ...")
